// Code generated by goadlc v3 - DO NOT EDIT.
package annotations

import (
	"fmt"
)

type AllowUntaggedDeserializeOfFirstBranch = struct{}

type CustomSerialization = bool

type DiscriminatorConfig struct {
	Branch DiscriminatorConfigBranch
}

type DiscriminatorConfigBranch interface {
	isDiscriminatorConfigBranch()
}

func (*DiscriminatorConfig) MakeNewBranch(key string) (any, error) {
	switch key {
	case "by_type":
		return &_DiscriminatorConfig_By_type{}, nil
	case "obj_props":
		return &_DiscriminatorConfig_Obj_props{}, nil
	}
	return nil, fmt.Errorf("unknown branch is : %s", key)
}

type _DiscriminatorConfig_By_type struct {
	V struct{} `branch:"by_type"`
}
type _DiscriminatorConfig_Obj_props struct {
	V ObjectProperties `branch:"obj_props"`
}

func (_DiscriminatorConfig_By_type) isDiscriminatorConfigBranch()   {}
func (_DiscriminatorConfig_Obj_props) isDiscriminatorConfigBranch() {}

func Make_DiscriminatorConfig_by_type() DiscriminatorConfig {
	return DiscriminatorConfig{
		_DiscriminatorConfig_By_type{struct{}{}},
	}
}

func Make_DiscriminatorConfig_obj_props(v ObjectProperties) DiscriminatorConfig {
	return DiscriminatorConfig{
		_DiscriminatorConfig_Obj_props{v},
	}
}

func (un DiscriminatorConfig) Cast_by_type() (struct{}, bool) {
	br, ok := un.Branch.(_DiscriminatorConfig_By_type)
	return br.V, ok
}

func (un DiscriminatorConfig) Cast_obj_props() (ObjectProperties, bool) {
	br, ok := un.Branch.(_DiscriminatorConfig_Obj_props)
	return br.V, ok
}

func Handle_DiscriminatorConfig[T any](
	_in DiscriminatorConfig,
	by_type func(by_type struct{}) T,
	obj_props func(obj_props ObjectProperties) T,
	_default func() T,
) T {
	switch _b := _in.Branch.(type) {
	case _DiscriminatorConfig_By_type:
		if by_type != nil {
			return by_type(_b.V)
		}
	case _DiscriminatorConfig_Obj_props:
		if obj_props != nil {
			return obj_props(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : DiscriminatorConfig")
}

func HandleWithErr_DiscriminatorConfig[T any](
	_in DiscriminatorConfig,
	by_type func(by_type struct{}) (T, error),
	obj_props func(obj_props ObjectProperties) (T, error),
	_default func() (T, error),
) (T, error) {
	switch _b := _in.Branch.(type) {
	case _DiscriminatorConfig_By_type:
		if by_type != nil {
			return by_type(_b.V)
		}
	case _DiscriminatorConfig_Obj_props:
		if obj_props != nil {
			return obj_props(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : DiscriminatorConfig")
}

type Doc = string

type ObjectProperties struct {
	Branch ObjectPropertiesBranch
}

type ObjectPropertiesBranch interface {
	isObjectPropertiesBranch()
}

func (*ObjectProperties) MakeNewBranch(key string) (any, error) {
	switch key {
	case "field":
		return &_ObjectProperties_Field{}, nil
	case "and":
		return &_ObjectProperties_And{}, nil
	case "or":
		return &_ObjectProperties_Or{}, nil
	case "not":
		return &_ObjectProperties_Not{}, nil
	}
	return nil, fmt.Errorf("unknown branch is : %s", key)
}

type _ObjectProperties_Field struct {
	V string `branch:"field"`
}
type _ObjectProperties_And struct {
	V []ObjectProperties `branch:"and"`
}
type _ObjectProperties_Or struct {
	V []ObjectProperties `branch:"or"`
}
type _ObjectProperties_Not struct {
	V ObjectProperties `branch:"not"`
}

func (_ObjectProperties_Field) isObjectPropertiesBranch() {}
func (_ObjectProperties_And) isObjectPropertiesBranch()   {}
func (_ObjectProperties_Or) isObjectPropertiesBranch()    {}
func (_ObjectProperties_Not) isObjectPropertiesBranch()   {}

func Make_ObjectProperties_field(v string) ObjectProperties {
	return ObjectProperties{
		_ObjectProperties_Field{v},
	}
}

func Make_ObjectProperties_and(v []ObjectProperties) ObjectProperties {
	return ObjectProperties{
		_ObjectProperties_And{v},
	}
}

func Make_ObjectProperties_or(v []ObjectProperties) ObjectProperties {
	return ObjectProperties{
		_ObjectProperties_Or{v},
	}
}

func Make_ObjectProperties_not(v ObjectProperties) ObjectProperties {
	return ObjectProperties{
		_ObjectProperties_Not{v},
	}
}

func (un ObjectProperties) Cast_field() (string, bool) {
	br, ok := un.Branch.(_ObjectProperties_Field)
	return br.V, ok
}

func (un ObjectProperties) Cast_and() ([]ObjectProperties, bool) {
	br, ok := un.Branch.(_ObjectProperties_And)
	return br.V, ok
}

func (un ObjectProperties) Cast_or() ([]ObjectProperties, bool) {
	br, ok := un.Branch.(_ObjectProperties_Or)
	return br.V, ok
}

func (un ObjectProperties) Cast_not() (ObjectProperties, bool) {
	br, ok := un.Branch.(_ObjectProperties_Not)
	return br.V, ok
}

func Handle_ObjectProperties[T any](
	_in ObjectProperties,
	field func(field string) T,
	and func(and []ObjectProperties) T,
	or func(or []ObjectProperties) T,
	not func(not ObjectProperties) T,
	_default func() T,
) T {
	switch _b := _in.Branch.(type) {
	case _ObjectProperties_Field:
		if field != nil {
			return field(_b.V)
		}
	case _ObjectProperties_And:
		if and != nil {
			return and(_b.V)
		}
	case _ObjectProperties_Or:
		if or != nil {
			return or(_b.V)
		}
	case _ObjectProperties_Not:
		if not != nil {
			return not(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : ObjectProperties")
}

func HandleWithErr_ObjectProperties[T any](
	_in ObjectProperties,
	field func(field string) (T, error),
	and func(and []ObjectProperties) (T, error),
	or func(or []ObjectProperties) (T, error),
	not func(not ObjectProperties) (T, error),
	_default func() (T, error),
) (T, error) {
	switch _b := _in.Branch.(type) {
	case _ObjectProperties_Field:
		if field != nil {
			return field(_b.V)
		}
	case _ObjectProperties_And:
		if and != nil {
			return and(_b.V)
		}
	case _ObjectProperties_Or:
		if or != nil {
			return or(_b.V)
		}
	case _ObjectProperties_Not:
		if not != nil {
			return not(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : ObjectProperties")
}

type SerializedName = string

type SerializedWithInternalTag struct {
	_SerializedWithInternalTag
}

type _SerializedWithInternalTag struct {
	Tag string `json:"tag"`
}

func MakeAll_SerializedWithInternalTag(
	tag string,
) SerializedWithInternalTag {
	return SerializedWithInternalTag{
		_SerializedWithInternalTag{
			Tag: tag,
		},
	}
}

func Make_SerializedWithInternalTag(
	tag string,
) SerializedWithInternalTag {
	ret := SerializedWithInternalTag{
		_SerializedWithInternalTag{
			Tag: tag,
		},
	}
	return ret
}

type TypeDiscrimination struct {
	_TypeDiscrimination
}

type _TypeDiscrimination struct {
	Disc_cfg DiscriminatorConfig `json:"disc_cfg"`
	Version  uint32              `json:"@v"`
}

func MakeAll_TypeDiscrimination(
	disc_cfg DiscriminatorConfig,
	version uint32,
) TypeDiscrimination {
	return TypeDiscrimination{
		_TypeDiscrimination{
			Disc_cfg: disc_cfg,
			Version:  version,
		},
	}
}

func Make_TypeDiscrimination(
	version uint32,
) TypeDiscrimination {
	ret := TypeDiscrimination{
		_TypeDiscrimination{
			Disc_cfg: ((*TypeDiscrimination)(nil)).Default_disc_cfg(),
			Version:  version,
		},
	}
	return ret
}

func (*TypeDiscrimination) Default_disc_cfg() DiscriminatorConfig {
	return Make_DiscriminatorConfig_by_type()
}
