// Code generated by goadlc v3 - DO NOT EDIT.
package annotations

import ()

type CustomSerialization = bool

type Doc = string

type SerializedName = string

type SerializedWithInternalTag struct {
	_SerializedWithInternalTag
}

type _SerializedWithInternalTag struct {
	Tag string `json:"tag"`
}

func MakeAll_SerializedWithInternalTag(
	tag string,
) SerializedWithInternalTag {
	return SerializedWithInternalTag{
		_SerializedWithInternalTag{
			Tag: tag,
		},
	}
}

func Make_SerializedWithInternalTag(
	tag string,
) SerializedWithInternalTag {
	ret := SerializedWithInternalTag{
		_SerializedWithInternalTag{
			Tag: tag,
		},
	}
	return ret
}
