// Code generated by goadlc v3 - DO NOT EDIT.
package java

import ()

type JavaCustomType struct {
	_JavaCustomType
}

type _JavaCustomType struct {
	Javaname     string `json:"javaname"`
	Ctorjavaname string `json:"ctorjavaname"`
	Helpers      string `json:"helpers"`
	GenerateType bool   `json:"generateType"`
}

func MakeAll_JavaCustomType(
	javaname string,
	ctorjavaname string,
	helpers string,
	generatetype bool,
) JavaCustomType {
	return JavaCustomType{
		_JavaCustomType{
			Javaname:     javaname,
			Ctorjavaname: ctorjavaname,
			Helpers:      helpers,
			GenerateType: generatetype,
		},
	}
}

func Make_JavaCustomType(
	javaname string,
	helpers string,
) JavaCustomType {
	ret := JavaCustomType{
		_JavaCustomType{
			Javaname:     javaname,
			Ctorjavaname: ((*JavaCustomType)(nil)).Default_ctorjavaname(),
			Helpers:      helpers,
			GenerateType: ((*JavaCustomType)(nil)).Default_generateType(),
		},
	}
	return ret
}

func (*JavaCustomType) Default_ctorjavaname() string {
	return ""
}
func (*JavaCustomType) Default_generateType() bool {
	return false
}

type JavaGenerate = bool

type JavaPackage = string
