// Code generated by goadlc v3 - DO NOT EDIT.
package typescript

import (
	goadl "github.com/adl-lang/goadl_rt/v3"
	"github.com/adl-lang/goadl_rt/v3/customtypes"
	"github.com/adl-lang/goadl_rt/v3/sys/adlast"
	"github.com/adl-lang/goadl_rt/v3/sys/types"
)

func Texpr_TypescriptGenerate() adlast.ATypeExpr[TypescriptGenerate] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("adlc.config.typescript", "TypescriptGenerate"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[TypescriptGenerate](te)
}

func AST_TypescriptGenerate() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"TypescriptGenerate",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_type_(
			adlast.MakeAll_TypeDef(
				[]adlast.Ident{},
				adlast.MakeAll_TypeExpr(
					adlast.Make_TypeRef_primitive(
						"Bool",
					),
					[]adlast.TypeExpr{},
				),
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{adlast.Make_ScopedName("sys.annotations", "Doc"): "ADL module or declaration annotation to control\nwhether code is actually generated.\n"},
	)
	return adlast.Make_ScopedDecl("adlc.config.typescript", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("adlc.config.typescript", "TypescriptGenerate"),
		AST_TypescriptGenerate(),
	)
}
