// Code generated by goadlc v3 - DO NOT EDIT.
package dynamic

import (
	"github.com/adl-lang/goadl_rt/v3/sys/adlast"
)

type Dynamic struct {
	_Dynamic
}

type _Dynamic struct {
	TypeExpr adlast.TypeExpr `json:"typeExpr"`
	Value    any             `json:"value"`
}

func MakeAll_Dynamic(
	typeexpr adlast.TypeExpr,
	value any,
) Dynamic {
	return Dynamic{
		_Dynamic{
			TypeExpr: typeexpr,
			Value:    value,
		},
	}
}

func Make_Dynamic(
	typeexpr adlast.TypeExpr,
	value any,
) Dynamic {
	ret := Dynamic{
		_Dynamic{
			TypeExpr: typeexpr,
			Value:    value,
		},
	}
	return ret
}
