// Code generated by goadlc v3 - DO NOT EDIT.
package goadl

import (
	. "github.com/adl-lang/goadl_rt/v3/adlc/config/go_"
	"github.com/adl-lang/goadl_rt/v3/customtypes"
	"github.com/adl-lang/goadl_rt/v3/sys/adlast"
	"github.com/adl-lang/goadl_rt/v3/sys/types"
)

func Texpr_GoCustomType() ATypeExpr[GoCustomType] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("adlc.config.go_", "GoCustomType"),
		),
		[]adlast.TypeExpr{},
	)
	return ATypeExpr[GoCustomType]{
		Value: te,
	}
}

func AST_GoCustomType() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"GoCustomType",
		types.Make_Maybe_nothing[uint32](
			struct{}{},
		),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"gotype",
						"gotype",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"adlc.config.go_",
									"GoType",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](
							struct{}{},
						),
						customtypes.MapMap[adlast.ScopedName, any]{adlast.Make_ScopedName("sys.annotations", "Doc"): "The Go struct to use\n\nNote currently interfaces are not supported\n"},
					),
					adlast.MakeAll_Field(
						"helpers",
						"helpers",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"adlc.config.go_",
									"GoHelperType",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](
							struct{}{},
						),
						customtypes.MapMap[adlast.ScopedName, any]{adlast.Make_ScopedName("sys.annotations", "Doc"): "The Go structed which implements json Marshal and Unmarshal for the gotype.\n\nNote Marshal and Unmarshal must be implemented for the specified struct's nil ptr\n"},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{adlast.Make_ScopedName("sys.annotations", "Doc"): "ADL declaration annotation to specify the custom type to use\n"},
	)
	return adlast.ScopedDecl{
		ModuleName: "adlc.config.go_",
		Decl:       decl,
	}
}

func init() {
	RESOLVER.Register(
		adlast.ScopedName{ModuleName: "adlc.config.go_", Name: "GoCustomType"},
		AST_GoCustomType(),
	)
}

func Texpr_GoHelperType() ATypeExpr[GoHelperType] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("adlc.config.go_", "GoHelperType"),
		),
		[]adlast.TypeExpr{},
	)
	return ATypeExpr[GoHelperType]{
		Value: te,
	}
}

func AST_GoHelperType() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"GoHelperType",
		types.Make_Maybe_nothing[uint32](
			struct{}{},
		),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"name",
						"name",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](
							struct{}{},
						),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"pkg",
						"pkg",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](
							struct{}{},
						),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"import_path",
						"import_path",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](
							struct{}{},
						),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.ScopedDecl{
		ModuleName: "adlc.config.go_",
		Decl:       decl,
	}
}

func init() {
	RESOLVER.Register(
		adlast.ScopedName{ModuleName: "adlc.config.go_", Name: "GoHelperType"},
		AST_GoHelperType(),
	)
}

func Texpr_GoType() ATypeExpr[GoType] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("adlc.config.go_", "GoType"),
		),
		[]adlast.TypeExpr{},
	)
	return ATypeExpr[GoType]{
		Value: te,
	}
}

func AST_GoType() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"GoType",
		types.Make_Maybe_nothing[uint32](
			struct{}{},
		),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"name",
						"name",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](
							struct{}{},
						),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"pkg",
						"pkg",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](
							struct{}{},
						),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"import_path",
						"import_path",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](
							struct{}{},
						),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.ScopedDecl{
		ModuleName: "adlc.config.go_",
		Decl:       decl,
	}
}

func init() {
	RESOLVER.Register(
		adlast.ScopedName{ModuleName: "adlc.config.go_", Name: "GoType"},
		AST_GoType(),
	)
}
