// Code generated by goadlc v3 - DO NOT EDIT.
package cpp

import ()

type CppCustomType struct {
	_CppCustomType
}

type _CppCustomType struct {
	Cppname             string    `json:"cppname"`
	Cppincludes         []Include `json:"cppincludes"`
	DeclarationCode     []string  `json:"declarationCode"`
	SerialisationCode   []string  `json:"serialisationCode"`
	GenerateOrigADLType string    `json:"generateOrigADLType"`
}

func MakeAll_CppCustomType(
	cppname string,
	cppincludes []Include,
	declarationcode []string,
	serialisationcode []string,
	generateorigadltype string,
) CppCustomType {
	return CppCustomType{
		_CppCustomType{
			Cppname:             cppname,
			Cppincludes:         cppincludes,
			DeclarationCode:     declarationcode,
			SerialisationCode:   serialisationcode,
			GenerateOrigADLType: generateorigadltype,
		},
	}
}

func Make_CppCustomType(
	cppname string,
) CppCustomType {
	ret := CppCustomType{
		_CppCustomType{
			Cppname:             cppname,
			Cppincludes:         ((*CppCustomType)(nil)).Default_cppincludes(),
			DeclarationCode:     ((*CppCustomType)(nil)).Default_declarationCode(),
			SerialisationCode:   ((*CppCustomType)(nil)).Default_serialisationCode(),
			GenerateOrigADLType: ((*CppCustomType)(nil)).Default_generateOrigADLType(),
		},
	}
	return ret
}

func (*CppCustomType) Default_cppincludes() []Include {
	return []Include{}
}
func (*CppCustomType) Default_declarationCode() []string {
	return []string{}
}
func (*CppCustomType) Default_serialisationCode() []string {
	return []string{}
}
func (*CppCustomType) Default_generateOrigADLType() string {
	return ""
}

type Include struct {
	_Include
}

type _Include struct {
	Name   string `json:"name"`
	System bool   `json:"system"`
}

func MakeAll_Include(
	name string,
	system bool,
) Include {
	return Include{
		_Include{
			Name:   name,
			System: system,
		},
	}
}

func Make_Include(
	name string,
	system bool,
) Include {
	ret := Include{
		_Include{
			Name:   name,
			System: system,
		},
	}
	return ret
}
